### ISSUE TITLE
RetoCCCF

### ISSUE THREAD

**Issue by pablarce** [mmasias/prg1-22-23#121]
Sobre el reto ampliado, muy difícilmente se llega a las 15 personas en cola, habría que subir la probabilidad o bajar el limite de gente.

**Comment by JoseSalceda** [comment]
Coincido, está dificil llegar a ese punto

**Comment by mmasias** [comment]
Epa!!! Pongamos entonces la probabilidad de llegada a un valor mayor: ¿70%?

Y ya que reflexionamos acerca de esto, ¿como ven el permitir ajustar esa probabilidad introduciendo el concepto de hora punta? ¿Y si la probabilidad es de 70% entre las 11:00h y las 13:00h y entre las 17:00h y las 19:00h? 😉

**Comment by mmasias** [comment]
¿Damos el issue por cerrado? Voy a aprovechar y corrijo el enunciado del problema para que quede con una probabilidad mayor, digamos del 50%.
@pablarce, si lo das por bueno, cierra el issue (en cuanto veas que he corregido el enunciado, claro!)
