### ISSUE TITLE
Carpetas de mas en mi fork

### ISSUE THREAD

**Issue by Dievex** [mmasias/prg1-22-23#17]
Buenas noches Manuel, primero de todo disculpa las molestias, quería hacerte una consulta a cerca de mi fork y el de varios compañeros a los que nos pasa lo mismo y es que en la carpeta de entregas de retos nos salen las carpetas de mas compañeros y no sabemos porque es ni como solucionarlo, adjunto imagen. Un saludo,

Diego García Niño.
![image](https://user-images.githubusercontent.com/94009483/196793305-ee585edc-d5f8-475b-9b69-ceac4fac5800.png)

**Comment by mmasias** [comment]
Sí: me di cuenta esta mañana cuando estuve repasando el código... Ha sido un despiste mío por ir muy rápido y no afinar la entrega 😞

En la próxima clase debatimos el tema y resolvemos -en vivo- este pequeño impase. 

¡Gracias por avisar!
