### ISSUE TITLE
Viaje de Marco error

### ISSUE THREAD

**Issue by srgiom** [mmasias/prg1-22-23#248]
Hola, he intentado hacer el viaje de Marco con métodos pero me da un error y no consigo ver cual es, si pudieras decirme que esta mal te lo agradecería.

public class viajeDeMarco_ConMetodos {
    public static void main(String[] args){

        float recorridoMadre = 350;
        float recorridoMarco = 0;
        float contadorDias = 0;
        float horasTrayecto = 0;
        float velocidadMarco = 0;
        float probabiliadLluviaFuerte = 0;
        float probabilidadLluviaNormal = 0;
        float probabilidadMonoCansado= 0;
        float probabilidadMonoEscape = 0;

        do{
            contadorDias++;

            System.out.println("+++++++++++ Dia " + contadorDias + " +++++++++++");
            datosMarco(contadorDias, horasTrayecto, probabilidadMonoCansado, probabilidadMonoEscape);
            distanciaMarco(recorridoMarco, horasTrayecto, velocidadMarco);
            datosMadre(recorridoMadre);
            System.out.println("++++++++++++++++++++++");

        } while (recorridoMarco < recorridoMadre);

        encuentro(recorridoMadre, recorridoMadre, contadorDias);

    }

static void datosMarco(float velocidadMarco, float horasTrayecto, float probabiliadLluviaFuerte, float probabilidadLluviaNormal){

    velocidadMarco = (int)(Math.random()*6)+10;
    probabiliadLluviaFuerte = (int)(Math.random()*10)+1;
    probabilidadLluviaNormal = (int)(Math.random()*100)+1;
    horasTrayecto = (int)(Math.random()*3)+8;

    Mono(probabiliadLluviaFuerte, probabilidadLluviaNormal, velocidadMarco, horasTrayecto);
    Lluvia(probabiliadLluviaFuerte, probabilidadLluviaNormal, probabilidadLluviaNormal);

    System.out.print("La velocidad de Marco hoy ha sido de " + velocidadMarco + "km/h");
    System.out.println(" ");
    System.out.print("Y ha viajado " + horasTrayecto + " horas");
    System.out.println(" ");
}

static void distanciaMarco(float recorridoMarco, float horasTrayecto, float velocidadMarco){
    recorridoMarco = horasTrayecto * velocidadMarco;
    System.out.println("Marco ha recorrido hoy " + recorridoMarco + "km");
    System.out.println(" ");
}

static void datosMadre(float recorridoMadre){
    recorridoMadre = recorridoMadre + 80;
    System.out.println("Hoy la madre esta a " + recorridoMadre + "km");
    System.out.println(" ");
}

static void Mono(float probabilidadMonoCansado, float probabilidadMonoEscape, float velocidadMarco, float horasTrayecto){
    probabilidadMonoCansado= (int)(Math.random()*100)+1;
    probabilidadMonoEscape = (int)(Math.random()*100)+1;

    if (probabilidadMonoCansado <= 25){
        velocidadMarco = velocidadMarco *90/100;
        System.out.println("El mono se ha cansado, la velocidad de marcos se reduce en un 10%, pasando a ser " + velocidadMarco + "km/h");
        System.out.println(" ");
    } else (probabilidadMonoEscape <= 15){
        horasTrayecto = horasTrayecto - 2;
        System.out.println("El mono se ha escapado, Marco ha perdido 2 horas, pasando a tener " + horasTrayecto + "h");
        System.out.println(" ");
    }
}

static void Lluvia(float probabiliadLluviaFuerte, float probabilidadLluviaNormal, float velocidadMarco){
    if (probabiliadLluviaFuerte == 1){
        velocidadMarco = velocidadMarco * 60/100;
        System.out.println("Hoy hay lluvia fuerte, la velocidad se reduce a " + velocidadMarco + "km/h");
        System.out.println(" ");
    }
    if (probabilidadLluviaNormal <= 30){
        velocidadMarco = velocidadMarco * 75/100;
        System.out.println("Hoy hay lluvia normal, la velocidad se reduce a " + velocidadMarco + "km/h");
        System.out.println(" ");
    }
}

static void encuentro(float recorridoMadre, float recorridoMarco, float contadorDias){

    if (recorridoMarco >= recorridoMadre){
        System.out.println("-------------------------------------------------------------------");
        System.out.println("Marco ha tardado " + contadorDias + " dias, en encontrar a su madre");
        System.out.println("-------------------------------------------------------------------");
    }

}

}

**Comment by mmasias** [comment]
Dale un vistazo a lo comentado en [este issue](https://github.com/mmasias/prg1-22-23/issues/252)
