### ISSUE TITLE
Control de divisor sin bucles

### ISSUE THREAD

**Issue by joserasilla-uneat** [mmasias/prg1-22-23#31]
Buenas tardes Manuel,
Haciendo los retos de hoy, en el que nos pides "Escriba un programa que pregunte dos números al usuario y realice la división de dos números, siempre y cuando el usuario no pida dividir por cero.", veo que hay que controlar que el usuario no ponga 0.
Para mi lo más sencillo es hacer un bucle do while, pero al no haberlos visto aún en clase, no se si eso te sirve. 
Machacándome la cabeza de como hacerlo con ifs, solo veo viable darle un numero limitado de intentos al usuario.
La otra opción es que te refieras a restringir la operación y no la solicitud de un número, en cuyo caso entiendo solo sería no hacer la cuenta si el número es 0.
Un saludo.

**Comment by mmasias** [comment]
Jose Manuel

Si el usuario pone cero, el programa le dice que ha puesto cero y finaliza: en efecto, si aún no hemos aprendido bucles, no podemos iterar

**Comment by joserasilla-uneat** [comment]
Perfecto, muchas gracias!
