### ISSUE TITLE
Carpetas borradas

### ISSUE THREAD

**Issue by lostal** [mmasias/prg1-22-23#35]
Buenas tardes Manuel, hay un problema con la carpeta dedicada con los retos (prg1-22-23/retos/entregas/). He ido a subir la tarea de hoy y he visto que mi carpeta ha sido borrada al sincronizarse con tu repo, y puedo ver carpetas ajenas a mi cuenta. He compartido mi problema con varios compañeros y les sucede lo mismo. Te adjunto la captura; muchas gracias de antemano.
![Problema GitHub](https://user-images.githubusercontent.com/114483337/197831880-b6b5d2c3-6811-4f69-908b-08ac4f9df498.png)

**Comment by mmasias** [comment]
Uhm... Tienes razón (y lo comentamos brevemente en clase hoy), y es que en lugar de acumularse las carpetas (que debería ser lo que ocurra), están pisándose porque **creo** que alguien ha hecho un fork tardío, que ya incluía unas cuantas carpetas.

De todos modos, es que me interesa mucho que quede todo comentado, para que puedan ver tanto el código propio, el de sus compañeros y los comentamos. Mañana dejamos definida una forma de envío que evite este problema: igual un pull-request a una rama de revisión. 

¡Gracias por avisar!
